### ISSUE TITLE
脚本显示Bug

### ISSUE THREAD

**Issue by AlphaINF** [linkedlist771/infiniteGPT4#1]
我想确认下脚本的逻辑
该脚本是否是在有GPT-4常规额度的情况下，优先使用GPT-4常规额度（即电脑版额度）
使用完GPT-4额度后，在勾选GPT-3.5的情况下，采用GPT-4-mobile进行问答。
在这种情况下，用户无法直接分辨出这个3.5其实是4，望进行一些提示。

**Comment by linkedlist771** [comment]
你好，谢谢你的issue。

- 第一个问题，代码的调用逻辑是这样的，代码写的比较清楚：

```javascript
                if (data.hasOwnProperty('model')&& (!data.model.includes('gpt-4'))) {
                    data.model = 'gpt-4-mobile';
                    init.body = JSON.stringify(data);
                }
```

首先判断该模型是否调用`GPT-4`模型，如果是那么不做任何修改，如果是默认的`GPT-3.5`模型，则修改为`GPT-4-mobile`，并不会影响对于`GPT-4`的正常使用，关于改进[[lencx/ChatGPT:]]( https://github.com/lencx/ChatGPT/releases)已经给出了一种较为优雅的解决方案，我目前还没有时间继续维护这个项目，如果你有好的建议，欢迎建立Pull Request。

- 第二个问题， 关于`GPT-4-mobile`模型的调用限制，这个我没测试过，因为是个人使用，加上生成速度限制，基本没有达到您说的`30/小时`的限制，关于构建大规模使用的时候可能存在这个问题， `建立账号池`维护API调用是否能高效解决呢？ 抱歉最近真的没时间维护这个项目了。

希望我的解答对您有用。

**Comment by linkedlist771** [comment]
目前openai已添加对这个模型的限制，现在我要关闭这个issue了， 此代码已作废。
